# Generated by Django 3.2 on 2022-11-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autos',
            options={'verbose_name_plural': 'Autos'},
        ),
        migrations.AlterModelTable(
            name='autos',
            table='autos',
        ),
    ]
