# Generated by Django 3.2 on 2023-02-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20221118_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autos',
            old_name='renta',
            new_name='precio',
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(default='SOME STRING', max_length=250)),
                ('id_auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.autos')),
            ],
        ),
    ]
