# Generated by Django 3.2 on 2023-02-10 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_auto_20230210_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.autos'),
        ),
    ]
